# Site settings
title: Robson Outfitters
email: robsonoutfitters@silverstar.com
description: > # this means to ignore newlines until "baseurl:"
  Robson Outfitters specializes in quality archery, and guided rifle hunts for trophy deer, elk, bear, grouse, duck and geese in Eastern Idaho.
  Teton Valley, Rexburg, Driggs, Tetonia, Felt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.robsonoutfitters.com" # the base hostname & protocol for your site
slogan: "Specializing in Big Game and Wilderness Adventures!"

# Build settings
markdown: kramdown
